# Generated by Django 4.2 on 2023-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newspost_delete_newsindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='number_of_views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
