# Generated by Django 4.2 on 2023-05-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='my_model_photos/'),
        ),
    ]
