# Generated by Django 4.2 on 2023-05-10 09:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
    ]
